; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes='cgscc(inline),function(sroa,gvn)' -S | FileCheck %s
;
; Test demonstrating type-based devirtualization via llvm.type.test+assume.
;
; Case f: static_cast<Impl*>(intf) annotated with llvm.type.test+assume - DOES devirtualize
; Case g: Copy constructor visible - vtable store visible - DOES devirtualize
; Case h: Parameter of known type - no type annotation - does NOT devirtualize
;

; C++ source code:
;
; int glob = 0;
; int secretValue = 42;
;
; struct Intf {
;   void foo() { this->doFoo(); }
;
;   virtual void doFoo();
; };
;
; struct Impl final : Intf {
;   void doFoo() override { glob = secretValue; }
; };
;
; void f(Intf *intf) { static_cast<Impl *>(intf)->foo(); }
;
; void g(Intf *intf) {
;   Impl copy = static_cast<Impl &>(*intf);
;   copy.foo();
; }
;
; void h(Impl intf) { intf.foo(); }


%struct.Impl = type { %struct.Intf }
%struct.Intf = type { ptr }

@glob = dso_local global i32 0, align 4
@secretValue = dso_local global i32 42, align 4
@_ZTV4Impl = linkonce_odr unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr null, ptr @_ZN4Impl5doFooEv] }, align 8

; Case f: static_cast<Impl*>(intf) annotated with llvm.type.test+assume.
; Clang emits type.test on the object pointer at CK_BaseToDerived cast sites.
; tryPromoteCall finds the type.test, resolves _ZTS4Impl -> _ZTV4Impl via the
; Itanium ABI naming convention, and promotes the indirect virtual call.
define dso_local void @_Z1fP4Intf(ptr noundef %intf) {
; CHECK-LABEL: define dso_local void @_Z1fP4Intf(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i1 @llvm.type.test(ptr [[INTF]], metadata !"_ZTS4Impl")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP0]])
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr @secretValue, align 4
; CHECK-NEXT:    store i32 [[TMP1]], ptr @glob, align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = call i1 @llvm.type.test(ptr %intf, metadata !"_ZTS4Impl")
  call void @llvm.assume(i1 %0)
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Case g: Copy constructor visible - DOES optimize (baseline working case)
define dso_local void @_Z1gP4Intf(ptr noundef %intf) {
; CHECK-LABEL: define dso_local void @_Z1gP4Intf(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @secretValue, align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr @glob, align 4
; CHECK-NEXT:    ret void
;
entry:
  %copy = alloca %struct.Impl, align 8
  call void @_ZN4ImplC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %copy, ptr noundef nonnull align 8 dereferenceable(8) %intf)
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %copy)
  ret void
}

; Case h: Parameter of known type - no type annotation - does NOT optimize.
; Without llvm.type.test+assume, no type information is available to the inliner.
define dso_local void @_Z1h4Impl(ptr noundef %impl) {
; CHECK-LABEL: define dso_local void @_Z1h4Impl(
; CHECK-SAME: ptr noundef [[IMPL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VTABLE_I:%.*]] = load ptr, ptr [[IMPL]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VTABLE_I]], align 8
; CHECK-NEXT:    call void [[TMP0]](ptr noundef nonnull align 8 dereferenceable(8) [[IMPL]])
; CHECK-NEXT:    ret void
;
entry:
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %impl)
  ret void
}

; Copy constructor (sets vtable)
define linkonce_odr void @_ZN4ImplC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %this, ptr noundef nonnull align 8 dereferenceable(8) %0) unnamed_addr align 2 {
entry:
  call void @_ZN4IntfC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %this, ptr noundef nonnull align 8 dereferenceable(8) %0)
  store ptr getelementptr inbounds ({ [3 x ptr] }, ptr @_ZTV4Impl, i32 0, i32 0, i32 2), ptr %this, align 8
  ret void
}

; Base copy constructor
define linkonce_odr void @_ZN4IntfC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %this, ptr noundef nonnull align 8 dereferenceable(8) %0) unnamed_addr align 2 {
entry:
  ret void
}

; Intf::foo() - non-virtual wrapper that makes the virtual call
define linkonce_odr void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %this) align 2 {
entry:
  %vtable = load ptr, ptr %this, align 8
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 0
  %0 = load ptr, ptr %vfn, align 8
  call void %0(ptr noundef nonnull align 8 dereferenceable(8) %this)
  ret void
}

; Impl::doFoo()
define linkonce_odr void @_ZN4Impl5doFooEv(ptr noundef nonnull align 8 dereferenceable(8) %this) unnamed_addr align 2 {
; CHECK-LABEL: define linkonce_odr void @_ZN4Impl5doFooEv(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr align 2 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @secretValue, align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr @glob, align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i32, ptr @secretValue, align 4
  store i32 %0, ptr @glob, align 4
  ret void
}
