; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes='cgscc(inline),function(sroa,gvn)' -S | FileCheck %s

; ModuleID = 'inline.cc'
source_filename = "inline.cc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.Impl = type { %struct.Intf }
%struct.Intf = type { ptr }

$_ZN4Intf3fooEv = comdat any

$_ZN4ImplC2ERKS_ = comdat any

$_ZN4IntfC2ERKS_ = comdat any

$_ZN4Impl5doFooEv = comdat any

$_ZTV4Impl = comdat any

$_ZTI4Impl = comdat any

$_ZTS4Impl = comdat any

@glob = dso_local global i32 0, align 4
@secretValue = dso_local global i32 42, align 4
@_ZTV4Impl = linkonce_odr dso_local unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI4Impl, ptr @_ZN4Impl5doFooEv] }, comdat, align 8
@_ZTI4Impl = linkonce_odr dso_local constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS4Impl, ptr @_ZTI4Intf }, comdat, align 8
@_ZTVN10__cxxabiv120__si_class_type_infoE = external global [0 x ptr]
@_ZTS4Impl = linkonce_odr dso_local constant [6 x i8] c"4Impl\00", comdat, align 1
@_ZTI4Intf = external constant ptr
@_ZTV4Intf = external unnamed_addr constant { [3 x ptr] }, align 8

; Function Attrs: mustprogress noinline optnone uwtable
define dso_local void @_Z1fP4Intf(ptr noundef %intf) #0 {
; CHECK-LABEL: define dso_local void @_Z1fP4Intf(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INTF_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[INTF]], ptr [[INTF_ADDR]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[INTF_ADDR]], align 8
; CHECK-NEXT:    call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) [[TMP0]])
; CHECK-NEXT:    ret void
;
entry:
  %intf.addr = alloca ptr, align 8
  store ptr %intf, ptr %intf.addr, align 8
  %0 = load ptr, ptr %intf.addr, align 8
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %0)
  ret void
}

; Function Attrs: mustprogress noinline optnone uwtable
define linkonce_odr dso_local void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %this) #0 comdat align 2 {
; CHECK-LABEL: define linkonce_odr dso_local void @_ZN4Intf3fooEv(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) #[[ATTR0]] comdat align 2 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[THIS1]], align 8
; CHECK-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[VFN]], align 8
; CHECK-NEXT:    call void [[TMP0]](ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  %vtable = load ptr, ptr %this1, align 8
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 0
  %0 = load ptr, ptr %vfn, align 8
  call void %0(ptr noundef nonnull align 8 dereferenceable(8) %this1)
  ret void
}

; Function Attrs: mustprogress noinline optnone uwtable
define dso_local void @_Z1gP4Intf(ptr noundef %intf) #0 {
; CHECK-LABEL: define dso_local void @_Z1gP4Intf(
; CHECK-SAME: ptr noundef [[INTF:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INTF_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[COPY:%.*]] = alloca [[STRUCT_IMPL:%.*]], align 8
; CHECK-NEXT:    store ptr [[INTF]], ptr [[INTF_ADDR]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[INTF_ADDR]], align 8
; CHECK-NEXT:    call void @_ZN4ImplC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) [[COPY]], ptr noundef nonnull align 8 dereferenceable(8) [[TMP0]]) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) [[COPY]])
; CHECK-NEXT:    ret void
;
entry:
  %intf.addr = alloca ptr, align 8
  %copy = alloca %struct.Impl, align 8
  store ptr %intf, ptr %intf.addr, align 8
  %0 = load ptr, ptr %intf.addr, align 8
  call void @_ZN4ImplC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %copy, ptr noundef nonnull align 8 dereferenceable(8) %0) #2
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %copy)
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define linkonce_odr dso_local void @_ZN4ImplC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %this, ptr noundef nonnull align 8 dereferenceable(8) %0) unnamed_addr #1 comdat align 2 {
; CHECK-LABEL: define linkonce_odr dso_local void @_ZN4ImplC2ERKS_(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]], ptr noundef nonnull align 8 dereferenceable(8) [[TMP0:%.*]]) unnamed_addr #[[ATTR1:[0-9]+]] comdat align 2 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[DOTADDR]], align 8, !nonnull [[META6:![0-9]+]], !align [[META7:![0-9]+]]
; CHECK-NEXT:    call void @_ZN4IntfC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]], ptr noundef nonnull align 8 dereferenceable(8) [[TMP1]]) #[[ATTR2]]
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV4Impl, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  %.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  store ptr %0, ptr %.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  %1 = load ptr, ptr %.addr, align 8, !nonnull !6, !align !7
  call void @_ZN4IntfC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %this1, ptr noundef nonnull align 8 dereferenceable(8) %1) #2
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV4Impl, i32 0, i32 0, i32 2), ptr %this1, align 8
  ret void
}

; Function Attrs: mustprogress noinline optnone uwtable
define dso_local void @_Z1h4Impl(ptr dead_on_return noundef %intf) #0 {
; CHECK-LABEL: define dso_local void @_Z1h4Impl(
; CHECK-SAME: ptr dead_on_return noundef [[INTF:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INTF_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[INTF]], ptr [[INTF_INDIRECT_ADDR]], align 8
; CHECK-NEXT:    call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) [[INTF]])
; CHECK-NEXT:    ret void
;
entry:
  %intf.indirect_addr = alloca ptr, align 8
  store ptr %intf, ptr %intf.indirect_addr, align 8
  call void @_ZN4Intf3fooEv(ptr noundef nonnull align 8 dereferenceable(8) %intf)
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define linkonce_odr dso_local void @_ZN4IntfC2ERKS_(ptr noundef nonnull align 8 dereferenceable(8) %this, ptr noundef nonnull align 8 dereferenceable(8) %0) unnamed_addr #1 comdat align 2 {
; CHECK-LABEL: define linkonce_odr dso_local void @_ZN4IntfC2ERKS_(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]], ptr noundef nonnull align 8 dereferenceable(8) [[TMP0:%.*]]) unnamed_addr #[[ATTR1]] comdat align 2 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV4Intf, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  %.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  store ptr %0, ptr %.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV4Intf, i32 0, i32 0, i32 2), ptr %this1, align 8
  ret void
}

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define linkonce_odr dso_local void @_ZN4Impl5doFooEv(ptr noundef nonnull align 8 dereferenceable(8) %this) unnamed_addr #1 comdat align 2 {
; CHECK-LABEL: define linkonce_odr dso_local void @_ZN4Impl5doFooEv(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR1]] comdat align 2 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @secretValue, align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr @glob, align 4
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  %0 = load i32, ptr @secretValue, align 4
  store i32 %0, ptr @glob, align 4
  ret void
}

attributes #0 = { mustprogress noinline optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { mustprogress noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { nounwind }

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = !{!"clang version 22.0.0git (https://github.com/llvm/llvm-project.git c2886a3fef2e6240928f1ac4cf3718df0402b0db)"}
!6 = !{}
!7 = !{i64 8}
;.
; CHECK: [[META6]] = !{}
; CHECK: [[META7]] = !{i64 8}
;.
